---
language: node_js 
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

language: python
python:
  - "3.6"
  - "nightly"

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get -qq update -y
  - sudo apt-get install gdal-bin -y

install:
  - pip install gdal bottle numpy
  - . install.sh

script:
  - . start.sh
