---
language: node_js 
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

language: python
python:
  - "3.6"
  - "nightly"

before_install:
  - sudo apt-get -qq update -y
  - sudo apt-get install python3-pip -y
  - sudo apt-get install libgdal-dev -y
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal

install:
  - pip install GDAL bottle numpy
  - . install.sh

script:
  - . start.sh
