---
language: node_js 
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

language: python
python:
  - "3.6"

before_install:
  - sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get -qq update -y
  - sudo apt-get install libgdal-dev -y
  - sudo apt-get install python-gdal

install:
  - pip install bottle numpy
  - sudo pip install Pillow
  - . install.sh

script:
  - . start.sh
